sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker
after_success:
- mvn clean test jacoco:report coveralls:report
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t maxdemarzi/guancialedb:latest .
- docker push maxdemarzi/guancialedb:latest