sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker
after_success:
- mvn clean test jacoco:report coveralls:report
- docker -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t docker.io/maxdemarzi/guancialedb:latest .
- docker push docker.io/maxdemarzi/guancialedb:latest